### PR TITLE
Implement more `backBehavior` options for SwitchRouter

### PR DESCRIPTION
**Pull request by satya164**

### CODE REVIEW

**Comment by ericvicenti** [comment]
This is good so far!

Lets some bikeshedding out of the way. Heres an idea for the names, feel free to suggest alternatives: (bold means its already in the API)

- **none**
- **initialRoute** - Back takes you to route 0
- back - Go to tab that comes before the current
- order - History stack with dedupe. Go back through tabs in the order you last visited them
- history - Infinite history stack.. (we probably don't even want to implement this?? there will never be a "pop")

**Comment by spencercarli** [comment]
Alternative names:

- tabOrder - Go to tab that comes before the current
- navigationOrder - History stack with dedupe. Go back through tabs in the order you last visited them

**Comment by satya164** [comment]
Let's settle on the following:

- `none` - don't handle the back button
- `history` - go back to previous route in history (with dedupe)
- `order` - go back to the tab with previous index (corresponds to the `order` config option)
- `initialRoute` - go back to the intial route (corresponds to the `initialRouteName` config option)

I haven't added the infinite history pattern since it doesn't sound useful.

**Comment by satya164** [comment]
@brentvatne @ericvicenti @spencercarli would you like any changes?

**Comment by ericvicenti** [comment]
Those options look great to me!

**Comment by brentvatne** [comment]
:+1: lgtm

**Comment by brentvatne** [comment]
@satya164 - can you update rfc according to template? then we can proceed with this

**Comment by satya164** [comment]
I'm working on a PR

**Comment by gameunite** [comment]
I really need this feature. Is there any workaround to make the history works? I want to go back to the previous screen instead of going back to the initialroute. Or do I have to implement my own stack and do the back manually?

**Comment by ericvicenti** [comment]
@gameunite, you can customize the TabRouter for your app using the following technique: 

https://next.reactnavigation.org/docs/custom-navigators.html#extending-navigators

By overriding `Navigator.router.getStateForAction`, you can customize the back behavior. Or you can fork the router yourself if you prefer.

**Comment by ericvicenti** [comment]
Looking forward to seeing this go forward! If somebody steps up to help, we may have this feature in time for the v2 release!

**Comment by Gloix** [comment]
I tested the Youtube app (version 13.15.55) and it falls within the `Keep a history of tabs, and de-duplicate` bucket, as opposed to the PR stating that it doesn't handle the back button.

**Comment by satya164** [comment]
They probably changed it. This was tested way long ago. Anyway, we want to provide options, so people can change it if they want.

**Comment by m1ck2** [comment]
Wouldn’t you implement a Ethereum or bitcoin router with block chain technology and it’s api I call as its road map. With react/navigation and machine learning it would have all you require but the serverless

**Comment by brentvatne** [comment]
all conversation is here, we need to finalize this RFC and then start implementation

**Comment by lustigdev** [comment]
@satya164 Need any help?

I'm not quite sure what the most 'official' way of doing this would be, but I got my preferred 'back' functionality (*history* as named above) by just modifying getStateForAction. Here's the code. Let me know if you want to use it or go in a different direction than this approach:

```
import React from 'react'
import { createBottomTabNavigator, NavigationActions } from 'react-navigation'
import { ProfileStack, AddPost } from '../Misc'
import FeedStack from '../Feed'
import MyCustomSillyDrawerComponent from '../MyCustomSillyDrawerComponent'
this.previousRoute = 'Main'
this.currentRoute = 'Main'
const TabNavigation = createBottomTabNavigator(
  {
    Main: FeedStack,
    AddPost: {
      screen: AddPost,
      navigationOptions: {
        tabBarVisible: false
      }
    },
    Profile: ProfileStack
  },
  {
    initialRouteName: 'Main',
    contentComponent: MyCustomSillyDrawerComponent
  }
)
const defaultGetStateForAction = TabNavigation.router.getStateForAction
TabNavigation.router.getStateForAction = (action, state) => {
  switch (action.type) {
    case 'Navigation/INIT':
      this.currentRoute = 'Main'
      this.nextRoute = 'Main'
      break
    case 'Navigation/NAVIGATE':
      this.previousRoute = this.currentRoute
      this.currentRoute = action.routeName
      this.nextRoute = action.routeName
      break
    case 'Navigation/BACK':
      this.nextRoute = this.previousRoute
      this.current = this.nextRoute
      this.previousRoute = this.currentRoute
      const index = state.routes.map(route => route.key).indexOf(this.nextRoute)
      const newState = {
        routes: state.routes,
        index: index
      }
      return newState
  }
  return defaultGetStateForAction(action, state)
}
export default () => <TabNavigation />
```

**Comment by forster-thomas** [comment]
Hy guys,
I got this error with that code. Can anyone help me?
Problem:
image


Code:
untitled 1

**Comment by brentvatne** [comment]
I'll fix this to match the template soon

**Comment by Er-rchydy** [comment]
@technoplato is there a workaround incase we use `DrawerNavigator ` instead of `createBottomTabNavigator ` ,  this is my code:
```
const MyDrawerNavigator = DrawerNavigator({
  Screen1: {
    screen: Screen1
  },
  Screen2: {
    screen: Screen2
  },
  Screen3: {
    screen: Screen3
  }
},
  {
    initialRouteName: 'Screen1',
    drawerPosition: 'left',
    backBehaviour: 'none',
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle'
  });
```
i added your code like this:
```
  const defaultGetStateForAction = MyDrawerNavigator.router.getStateForAction
  MyDrawerNavigator.router.getStateForAction = (action, state) => {
    switch (action.type) {
      case 'Navigation/INIT':
        this.currentRoute = 'Main'
        this.nextRoute = 'Main'
        break
      case 'Navigation/NAVIGATE':
        this.previousRoute = this.currentRoute
        this.currentRoute = action.routeName
        this.nextRoute = action.routeName
        break
      case 'Navigation/BACK':
        this.nextRoute = this.previousRoute
        this.currentRoute = this.nextRoute
        this.previousRoute = this.currentRoute
        const index = state.routes.map(route => route.key).indexOf(this.nextRoute)
        const newState = {
          routes: state.routes,
          index: index
        }
        return newState
    }
    return defaultGetStateForAction(action, state)
  }
```

but it didn't work, it messed the `DrawerNavigator`.
i hope you can find a way to make it work with `DrawerNavigator` too.
thanks

**Comment by slorber** [comment]
Hi,

I'd like to contribute this feature. Is someone already working on it?

**Comment by brentvatne** [comment]
@slorber - don't think so! this would be awesome if you could help!

**Comment by brentvatne** [comment]
@slorber - don't think so! this would be awesome if you could help!

**Comment by slorber** [comment]
here is a PR: https://github.com/react-navigation/react-navigation-core/pull/31

**Pull request merged**
